BLUEVIEW: use telodyne sdk instead of custom package
uf-mil/installer pull request #12
Opened 2017-04-19 04:15 UTC by ironmig

addresses #11

2017-04-19 09:56 UTC, sentree requested changes
This version of the script would clearly fail every time due to my last comment in this review. Any changed logic in the script needs to be tested in a bare chroot or virtual machine prior to merge (this means each condition). A docker rebuild will also have to be attempted prior to merge.

See #11 for other things that have to be done to get building to work.

2017-04-19 09:56 UTC, whispercoros commented on install.sh
>  	if [[ ! -d $CATKIN_DIR/src/bvtsdk ]]; then
Why did you not change this? Be sure you look over everything relating to the SDK.

2017-04-19 09:56 UTC, whispercoros commented on install.sh
>  	openssl enc -aes-256-cbc -d -pass file:<(echo -n $BVTSDK_PASSWORD) | tar -xpz
Am I correct in assuming that you used the same password and tested this decryption line verbatim?

2017-04-19 09:56 UTC, whispercoros commented on install.sh
> +	curl -s https://raw.githubusercontent.com/uf-mil/installer/master/libbvtsdk.tar.gz.enc | \
Why change the name of the encrypted archive, but not the directory it extracts to? I think the name should stay as is.

2017-04-19 09:56 UTC, whispercoros commented on install.sh
> +	cd $CATKIN_DIR/src/mil_common/drivers/mil_blueview_driver/
No trailing slash, here. The use of `cd` implies that it is a directory and it is not convention for the file.

2017-04-19 17:38 UTC, ironmig commented
Updated so it will extract tarball to ```~/.mil/bvtsdk```. Then it will symbolic link this to the correct location in the mil_blueview_driver, or if on docker just leave it there. Than the Jenkinsfile for SubjuGator / mil_common will link to to the mil_blueview_driver after they pull mil_common.

2017-04-19 17:41 UTC, ironmig commented
Let's try rebuilding the docker image today using my install script branch then manually pull my mil_common branch and build it like Jenkins would

2017-04-19 20:37 UTC, ironmig commented
Just tested on my own system. Does correctly download, decrypt, link to driver directory, and build. Just gatta check docker now.

2017-04-22 14:49 UTC, sentree requested changes
Looks a lot better now, I will test this with Docker once you make the changes. Be sure to mirror your changes in `user_install.sh` as those files need to stay in sync.

2017-04-22 14:49 UTC, whispercoros commented on install.sh
> +BVTSDK_DIR_COMPLETE=$BVTSDK_DIR/bvtsdk
Why create a new variable just to mirror `MIL_CONFIG_DIR`? I think it world be better to just use `BVTSDK_DIR` for what `BVTSDK_DIR_COMPLETE` is being used for and then remove `BVTSDK_DIR_COMPLETE`.

2017-04-22 14:49 UTC, whispercoros commented on install.sh
>  	openssl enc -aes-256-cbc -d -pass file:<(echo -n $BVTSDK_PASSWORD) | tar -xpz
Am I correct in assuming that you used the same password and tested this decryption line verbatim?

2017-04-22 14:49 UTC, whispercoros commented on install.sh
> +	curl -s https://raw.githubusercontent.com/uf-mil/installer/master/libbvtsdk.tar.gz.enc | \
Why change the name of the encrypted archive, but not the directory it extracts to?

2017-04-22 14:49 UTC, whispercoros commented on install.sh
> +		ln -s $BVTSDK_DIR_COMPLETE $CATKIN_DIR/src/mil_common/drivers/mil_blueview_driver/bvtsdk
Try to comment this block a bit more, it could be confusing for people not involved in developing the CI process.

2017-04-22 18:16 UTC, ironmig commented on install.sh
> +	curl -s https://raw.githubusercontent.com/uf-mil/installer/master/libbvtsdk.tar.gz.enc | \
I'm just mirroring the name the sdk comes as. It is distrubted as libbvtsdk.tar.gz and contains a bvtsdk directory.

2017-04-22 18:16 UTC, ironmig commented on install.sh
>  	openssl enc -aes-256-cbc -d -pass file:<(echo -n $BVTSDK_PASSWORD) | tar -xpz
Yee it works

2017-04-22 18:18 UTC, ironmig commented on install.sh
> +BVTSDK_DIR_COMPLETE=$BVTSDK_DIR/bvtsdk
I like it being it's own variable so it's easy to change one line (56) if we decide to put BVTSDK somewhere else like .local or something.

2017-04-22 22:18 UTC, sentree approved these changes
Looks good.

2017-04-22 22:18 UTC, merged