INSTALL: Add the Flycapture SDK to the install process
uf-mil/installer pull request #19
Opened 2017-07-15 07:05 UTC by whispercoros

This is the first of two pull requests that address uf-mil/installer#18. It adds the upstream Flycapture SDK to the list of available install options so the upstream `pointgrey_camera_driver` package can be used in `mil_common`. The install script provided with the driver assumed a lot of dependencies that are not available when installing on the barebones CI containers and had some pretty bad logic overall, so I adapted it to our needs. This installed properly on one of my test machines.

2017-07-15 22:45 UTC, kev-the-dev requested changes
I don't think this will work for users not installing flycap.

2017-07-15 22:45 UTC, ironmig commented on install.sh
> +cd /tmp/flycapture-2-2.11.3.121-amd64
It doesn't look like code is in an if guard. Shouldn't this only run if ```[][]{{||(([[ "$INSTALL_FLYCAP" == "true" ]]))||}}][[][]```

2017-07-16 05:02 UTC, whispercoros commented on install.sh
> +cd /tmp/flycapture-2-2.11.3.121-amd64
Ah, the effects of sleep deprivation. And almost, you missed the `; do` at the end of the line.

2017-07-16 19:22 UTC, kev-the-dev approved these changes

2017-07-16 22:54 UTC, merged